from winery.models import Wine

red_1 = Wine(name='Pinot Noir', type='Red', region='France')
red_2 = Wine(name='Cabernet Sauvignon', type='Red', region='France/Spain')
red_3 = Wine(name='Bobal', type='Red', region='Spain')
red_4 = Wine(name='Malbec', type='Red', region='France')
red_5 = Wine(name='Merlot', type='Red', region='France')
red_6 = Wine(name='Isabella', type='Red', region='Italy')
red_7 = Wine(name='Cinsaut', type='Red', region='France')
white_1 = Wine(name='Chardonnay', type='White', region='France')
white_2 = Wine(name='Sauvignon blanc', type='White', region='France')
white_3 = Wine(name='Riesling', type='White', region='Germany')
white_4 = Wine(name='Muscat', type='White', region='Italy/France/Australia/Spain')
lager_1 = Wine(name='Pilsner', type='Lager', region='Bohemia')
lager_2 = Wine(name='Bock', type='Lager', region='Germany')
lager_3 = Wine(name='Märzen', type='Lager', region='Bavaria')
lager_4 = Wine(name='Schwarzbier', type='Lager', region='Germany')
lager_5 = Wine(name='Helles', type='Lager', region='The fires of Hades')