"""empty message

Revision ID: 05692ddb87b0
Revises: b5892e17e8cd
Create Date: 2024-03-08 13:27:47.173160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05692ddb87b0'
down_revision = 'b5892e17e8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wine_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.wine_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'wine_id')
    )
    op.drop_table('shelf_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf_items',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('wine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='shelf_items_user_id_fkey'),
    sa.ForeignKeyConstraint(['wine_id'], ['wine.wine_id'], name='shelf_items_wine_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'wine_id', name='shelf_items_pkey')
    )
    op.drop_table('wine_users')
    # ### end Alembic commands ###
