"""empty message

Revision ID: 3dfe450acb4f
Revises: 05692ddb87b0
Create Date: 2024-03-08 16:48:32.681314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dfe450acb4f'
down_revision = '05692ddb87b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wine_users', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
